language: generic
sudo: required
services:
- docker
before_install:
- docker build -t poeclient:prod -f Dockerfile.prod .
script:
- docker run -e CI=true poeclient:prod npm run test
after_success:
- docker build -t poeclient:prod -f Dockerfile.prod .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push poeclient:prod
deploy:
  provider: heroku
  app: poeapp
  skip_cleanup: true
  api_key:
    secure: IpR4CzVH0khuNMN7u7d43lZcbJL3ulWH6qEZbG59grF0jxf0Lb7B7KwXMD71BbNuX1+3LBjTGNNMp6m2a+HrMw8HO3GHT7xpVCHiYBDLIMo4/+6H4dGe0fQx0s2tE1/FauQZ4XdNjqXa6+zyehiusIogX0POpNS0yHU2BNCmQOTxroE89JaGA1os3+ZTOcPE0RJdbdSv6XeXFvS+Qz5X5cH5iYFcohp+vghX9KQdxT6GqWFWz0D1TqlbL5TDCtfdPQruNpEGwbnSeLPo1Mvj9OcQUkavFbuN9SDuE5cIpXQ4F9B+Ch5bpH9B0p7Rm3MJvsfoRXmEqeR/ZKr1OA01G13c+EdEAOwh3P0sLcMgVzs++9WboYFexGtqHkqQnZ/ib542bhKLW2WgUCyTr7KJlkPk5T8zwOQDxos0Y7Ui+8jakkJG6fcNLJQYc//ALfvo2EDL5eheg82A9cwgvhoEIxlIG2gdFsarV1ibsyHFqUBV2HoAkkxAaaUoH9p7+AtfRaFlB0Ay/X14mVoUMWz0C1IhVc0khsaTwpeihEzuIDRHEWn+jkT0JC6Zu0ji3Dnvwlbx5XT45eCBMeM9mShbtnQS53ZP4MLcyCK7nBpUoiyCayG4TokTuJlkgX5aO32BD4+EdGxZsXHth7uYlXcrRdOAl/rOIhCEM5V5iWhd6q4=
