language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t poe/poeclient -f Dockerfile .

script:
  - docker run -e CI=true poe/poeclient npm run test

after_success:
  - docker build -t poe/poeclient -f Dockerfile . 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push poe/poeclient

# after_success:
#   - docker tag poe/poeclient registry.heroku.com/poeapp/web
#   - heroku login -i
#   - jsalaz1989@gmail.com
#   - Apollo13!
#   - heroku container:login
#   - heroku container:push web
#   - heroku container:release web

  #tri