language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t poeclient -f Dockerfile.dev .

script:
  - docker run -e CI=true poeclient npm run test

after_success:
  - docker build -t poeclient -f Dockerfile . 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push poeclient

# With Heroku CLI this is heroku login && heroku container:login && heroku container:push web && heroku container:release web
deploy:
  provider: heroku
  app: poeapp
  skip_cleanup: true  # get an error if you don't have this here