language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t poeclient -f Dockerfile.dev .

script:
  - docker run -e CI=true poeclient npm run test

# after_success:
#   - docker build -t poeclient -f Dockerfile . 
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker push poeclient

after_success:
  # - docker tag poe/poeclient registry.heroku.com/poeapp/web
  - (
      echo "$HEROKU_CREDENTIALS_EMAIL"
      echo "$HEROKU_CREDENTIALS_PASSWORD"
    ) | heroku login -i
  - heroku container:login
  - heroku container:push web
  - heroku container:release web

  #trig