language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t poe/poeclient -f Dockerfile .

script:
  - docker run -e CI=true poe/poeclient npm run test

after_success:
  - docker build -t poe/poeclient -f Dockerfile.prod . 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push poe/poeclient