version: '3.8'

services:

  frontend:
    container_name: poeclient
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'            # required for hot reloading, needs Dockerfile user = local user
      - '/app/node_modules' # avoids node_modules in Dockerfile build from being overwritten when mounting cwd
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
