version: '3.8'

services:

    frontend-prod:
        container_name: poeclientprod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '8877:80' 